### ISSUE TITLE
Define the project

### ISSUE THREAD

**Issue by Mte90** [Mte90/nopineapple.pizza#1]
My idea is something like: https://www.youtube.com/watch?v=ACmydtFDTGs

We are on github so no servers and AI so maybe we can do something like Tinder with a collection ho photo of real pizza and of crap food.
The user vote and on based on the chose do something like show a cool meme or a video on youtube.
With resources that are on other server for us can be simple to create different json and with javascript populate them on the page with this reactions.
Also will be easy to people to contribute with giving their stuff.

What do you think guys?

- 4 txt: 2 for pizza and crap food, 2 for good/bad answers (1 parameter for url and one for text)
- This value will be got randomly
- Showed fullscreen or something like that
- 2 big button
- After 5 vote invite to contribute on github
- Maybe also a donate button to pay the domain (20$ dollars for this year and 70 $ for the next one)

**Comment by Mte90** [comment]
@EugenioPetulla @edovio do you have any suggestions?

**Comment by Mte90** [comment]
I think that the instagram way is more cool http://joysocial.net/wp-content/uploads/2017/10/Instagram-Story-Polls-20.png

**Comment by Mte90** [comment]
First version with pick random stuff: http://nopineapple.pizza/

**Comment by EugenioPetulla** [comment]
I think you should do a sort of No Pineapple Pizza rulette.

Just a button that randomly picks a tweet or instagram image from the hashtag #nopineapplepizza and other similar tags and display it in a fancy way. If you push the button more then X times there will be an easter egg that show a predefined quote about how shitty is pineapple pizza! 😈 

Hashtag sources

- https://www.instagram.com/explore/tags/pineapplepizzasucks/
- https://www.instagram.com/explore/tags/nopineapplepizza/
- https://twitter.com/hashtag/nopineapplepizza?src=hash
- https://twitter.com/hashtag/pineapplepizzaban&src=hash
- https://twitter.com/hashtag/pineapplepizzasucks?src=hash

**Comment by Mte90** [comment]
Looking on this stuff is not possible to show the wrong stuff and good one because many of them are sarcastic.
I want to do a constructive way to teach people that they are bad people XD

**Comment by Mte90** [comment]
Maybe in the meantime that we find a way I was thinking that we can take randomly a post from:

- https://www.facebook.com/italiansmadatfood/
- https://twitter.com/italiancomments

The mainly problems that on twitter and on facebook there is no why to get the latest posts only with javascript without a proxy server.

**Comment by Mte90** [comment]
With https://twitrss.me/twitter_user_to_rss/?user=italiancomments we can get an rss of photos from a twitter account and later parse and cleaning.

**Comment by Mte90** [comment]
Since an year with nothing I think that we can do a simple page that explain why is bad
